# Generated by Django 2.2.7 on 2019-11-18 11:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('historyapp', '0001_initial'), ('historyapp', '0002_auto_20191118_0634'), ('historyapp', '0003_auto_20191118_0637'), ('historyapp', '0004_auto_20191118_0640'), ('historyapp', '0005_auto_20191118_0938')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EOSBlock',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('producer', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('new_producers', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_mroot', models.CharField(blank=True, max_length=255, null=True)),
                ('action_mroot', models.CharField(blank=True, max_length=255, null=True)),
                ('producer_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('header_extensions', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('ref_block_prefix', models.BigIntegerField(default=0)),
                ('confirmed', models.BigIntegerField(default=0)),
                ('schedule_version', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='EOSTransaction',
            fields=[
                ('txid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(default='executed', max_length=255)),
                ('compression', models.CharField(default='none', max_length=255)),
                ('cpu_usage_us', models.BigIntegerField(default=0)),
                ('net_usage_words', models.BigIntegerField(default=0)),
                ('signatures', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('context_free_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('packed_trx', models.TextField(blank=True, max_length=1000, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='historyapp.EOSBlock')),
            ],
        ),
        migrations.CreateModel(
            name='EOSAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('authorization', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('tx_from', models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='TX Sender (from data)')),
                ('tx_to', models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='TX Recipient (from data)')),
                ('tx_memo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='TX Memo (from data)')),
                ('tx_amount', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True, verbose_name='Amount of tokens transacted (from data)')),
                ('tx_precision', models.IntegerField(default=4, verbose_name='TX Token Decimal Places')),
                ('tx_symbol', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='TX Token Symbol (from data)')),
                ('hex_data', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='historyapp.EOSTransaction')),
                ('action_index', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('transaction', 'action_index')},
            },
        ),
    ]
