# Generated by Django 2.2.7 on 2019-11-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0001_squashed_0005_auto_20191118_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosblock',
            name='new_producers',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='eosblock',
            name='producer_signature',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
