# Generated by Django 2.2.7 on 2019-11-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0002_auto_20191122_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosaction',
            name='account',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='eosaction',
            name='tx_from',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='TX Sender (from data)'),
        ),
        migrations.AlterField(
            model_name='eosaction',
            name='tx_to',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='TX Recipient (from data)'),
        ),
    ]
