# Generated by Django 2.2.7 on 2020-01-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0004_auto_20200116_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosaction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
